spring.application.name=uber-backend
# Server Port
server.port=9090

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/ride_matching_db
spring.datasource.username=postgres
spring.datasource.password=hello

# Hibernate / JPA Settings (Yeh tera magic hai jo bina SQL ke table banayega)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Connection Settings
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Apache Kafka Configurations
spring.kafka.bootstrap-servers=localhost:9092

# Producer Config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer Config
spring.kafka.consumer.group-id=uber-ride-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer